### ISSUE TITLE
Connection protocols configuration problems

### ISSUE THREAD

**Issue by santiago-dev96** [tiagoit/mv-final-capstone-project#3]
The API is hardcoding the use of HTTP only connections when it is possible to force HTTPS and set the API to use that protocol. Configuration must change to this later possible scenario.

**EXTRA**:
- Redirection to the same page that requested the login to continue.
- Conversation like messages to providers instead of a small text input field.
- Remove double slash at URI for the connection with the Rails API.

**Comment by tiagoit** [comment]
- HTTPS set on the `.env.production` frontend file.
- SSL forced on `production.rb` backend configuration file.
